"""Build the exhaustive per-file appendix from the audited inventory and notes."""
import csv
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent

NOTES = {
"add_transformer_to_model_comparison.py": "Adds a parameter-budgeted Transformer to an existing five-model comparison. Checks original protocol metadata, shared seeds/counts and expected structure, then merges paired summaries. Useful consistency work, but it inherits the older training-data/validation conventions rather than the modern factorial CV protocol.",
"audit_validation_filtered_fusion_kddtest.py": "Post hoc fusion audit: filters candidates by OOF eligibility, scores survivors on saved KDDTest predictions, and ranks with test guards/gaps. Includes vectorized prediction, cache/process progress and test-aware ranking. Suitable for exploration; the resulting ranking cannot be treated as selection independent of KDDTest.",
"cnn_baseline.py": "Original small valid-convolution Conv2D CE pipeline, with data-to-grid preprocessing, checkpointing and reports. Fits preprocessing before internal validation separation and checkpoints validation accuracy. It is not the matched modern baseline and the old result figures should not be attributed to the new factorial experiment.",
"cnn_fin.py": "Original combined CNN/focal/CTGAN/undersampling experiment. Constructs augmented data before its validation split, so generator knowledge and synthetic validation examples weaken validation independence. Represents historical thesis development rather than the no-CTGAN OOF study.",
"cnn_focal.py": "Original smaller CNN with effective-number focal loss, serialization and reports. Full-data preprocessing/class counts precede internal validation splitting, and checkpoint selection uses validation accuracy. Useful historical loss comparison, but not the modern fixed-budget four-fold focal search.",
"cnn_gan_foc.py": "Defines reusable, registered ClassBalancedFocalLoss and effective-number weights used by newer code; also implements old CTGAN generation/training. True-class softmax focal formula is coherent. The conditional generator can force requested labels onto mismatched returned rows; old augmented validation is not independently generated. These legacy issues are outside modern no-CTGAN data flow.",
"cnn_opt.py": "Shared optimized Conv2D builder, class-score division and BalancedBatchSequence, plus a large legacy CTGAN training CLI. Batch guarantee correctly supplies available rare classes, but fills other positions with replacement. The modern backbone is residual/BN with roughly 109k parameters. Its legacy main has full-real-data preprocessing/generator provenance issues even though real validation is separated before appending synthetic rows.",
"cnn_opt_1d_4gpu.py": "Defines optimized Conv1D, MLP and scalar-feature-token Transformer builders used in the study, plus an older mirrored multi-GPU/CTGAN training CLI. Conv1D dense width 48 supports the later parameter budget. Legacy augmented validation differs from cnn_opt's updated real-only validation; global batch guarantees need not hold independently on every GPU replica.",
"compare_all_models.py": "Runs paired-seed Conv2D, Conv1D, MLP and ordinary/weighted XGBoost comparisons. Computes analytic neural counts and matching dense widths; writes plans, subprocess logs and merged metrics. Historical neural CTGAN and real-only XGBoost pipelines differ beyond architecture, and paired seed IDs alone do not ensure matching validation populations.",
"compare_cnn_1d_2d.py": "Orchestrates older 1D/2D comparisons with matched filter/dense parameter budgets and paired seeds. Reuses old training CLIs, so real-versus-augmented validation semantics can differ. Not the clean common-OOF four-architecture comparison described by the abstract.",
"compare_cnn_opt_xgboost.py": "Small orchestrator comparing enhanced CNN with class-weighted XGBoost. Launches subprocesses and collects outputs. The CNN requires synthetic-data inputs while XGBoost uses a different intervention; interpret as whole-pipeline comparison rather than a controlled backbone ablation.",
"cost_sensitive_xgboost.py": "Non-neural comparator: preprocesses tabular data, derives class-frequency sample weights and fits a multiclass XGBoost model with validation/report outputs. Provides useful tabular context but is not among the four backbones in the supplied abstract. Cost weights are an imbalance policy, not a demonstrated operational cyber-risk cost matrix.",
"evaluate_cnn_grid_winner.py": "Loads a selected legacy CNN grid model, validates available selection metadata and reports held-out results. Its default validation rank is 2 rather than 1, so the intended rank/configuration must be justified and recorded. Requires external grid artifacts absent from this checkout and does not reproduce the new eight-cell results.",
"evaluate_final_natural_rare_super_stack_kddtest.py": "Freezes architecture-specific natural-Rare-F1 stack configurations from OOF rankings, validates expert sources, refits the meta-model on training OOF data and applies it to test probabilities. Contains explicit acknowledgment of earlier test-driven fusion development. Strong inference/provenance checks, but a post hoc test assessment rather than a new untouched test.",
"evaluate_final_simple_average_vs_safe_stack_kddtest.py": "Applies frozen simple-average and safe-stack rules to three expert test sources. Validates architecture, epoch/batch settings, loss/batching/quota, selected focal parameters, parameter counts, no CTGAN, source hashes and probability structure; refuses distinct ambiguous sources. Its stronger semantic validation is a useful example for repairing the factorial evaluator.",
"grid_search_cnn_opt_4gpu.py": "Older grid orchestrator for optimized CNN synthetic amount/focal settings, with GPU queues, resumable run outputs and validation summaries. Its objectives/guarded decision selection differ from the current Rare-F1-first four-fold study. The checked-in grid plan demonstrates scheduled combinations, not completed execution.",
"random_search_cnn_opt_1d.py": "Samples legacy Conv1D architectural/training configurations and runs each trial through the old mirrored-GPU CLI. Supports 500-trial scheduling and optional validation-metric auto-summary. Expensive exploration of a different protocol; requires its own complete artifacts and explicit selection history.",
"run_cnn_ablation_4gpu.py": "Older staged CNN ablation with baseline, focal, naive CTGAN, integrated variants, batching and scaling. Reuses shared fitted models for some raw/scaled evaluations. It is a useful progression study but not a complete independent 2x2x2 of the abstract because CTGAN and integration choices are bundled.",
"run_ctgan_amount_sweep_4gpu.py": "Modern synthetic-amount sweep that splits real data first, fits GAN/preprocessing on training only, keeps validation real, and uses nested prefixes of larger generated pools for paired amount comparisons. This avoids a central legacy leakage problem. Its shared conditional generation helper still needs label/domain verification; it is outside the no-CTGAN factorial.",
"run_final_baseline_vs_full_kddtest_4gpu.py": "Final fixed-epoch all-KDDTrain fitting and KDDTest prediction runner for hardcoded frozen architectures/focal settings and legacy scale coefficients. Saves raw probabilities and detailed per-run metadata. Its older five-variant summary is not full factorial scoring. Resume identity omits source/data/environment/determinism fingerprints and completion does not link against the current feature cache.",
"run_final_single_enhancements_kddtest_4gpu.py": "Argument wrapper requesting focal_only, batch_only and scaling_only from the final runner. Needed historically to fill missing training regimes, but scaling_only uses the older fixed full-model coefficients. Use variant-specific postprocessing for the actual factorial S cells.",
"run_no_ctgan_model_ablation_4gpu.py": "Large shared core defining raw mapping, fixed category schema, fold-only preprocessing, ordered 121-feature arrays, metric calculation, class-balanced weights, score scaling, atomic outputs and source hashing. These helpers underpin current CV. Its own training CLI is an earlier stratified 80/20 ablation with validation checkpointing/early stopping, not the paper's four-fold fixed-epoch runner.",
"select_fusion_against_all_validation_baselines.py": "OOF-only selector requiring absolute Rare-F1 gains against all stand-alone baselines, with inner selection/complement refits and outer audit acceptance. Deliberately ignores legacy macro/MCC guards. Hardcoded search identity and adapted selection rule need retained provenance; nested meta-evaluation remains conditional on frozen expert OOF predictions.",
"summarize_trials.py": "Dependency-light parser/aggregator for historical trial reports. Its default macro_f1 ranking is a test metric; specify validation metrics for development selection. Missing/non-numeric observations can disappear from aggregation, so enforce expected seed/run completeness before comparing means.",
"sweep_fixed_backbone_imbalance_4gpu.py": "Earlier clean split-based sweep for three neural families plus ordinary/weighted XGBoost. Uses train-only preprocessing, focal grids and always-on neural rare batching; validation checkpoints and a guarded weaker-rare-recall scaling objective. It lacks the MLP/full four-fold factorial and should not supply interchangeable modern results.",
"transformer_baseline.py": "Thin entry point into the older multi-model trainer with Transformer architecture defaults. Despite the name, its inherited pipeline can include CTGAN/focal/batching enhancements. The current ordinary-CE Transformer baseline is run_transformer_baseline_cv_4gpu.py.",
"tune_cnn_opt_thresholds.py": "Legacy validation-time decision tuning for a saved optimized CNN, reconstructing preprocessing and real validation membership. Distinguish probability divisors from rejection thresholds used elsewhere. Relies on the older preprocessing/generator provenance, so its validation result is not equivalent to modern OOF coefficient selection.",
"tune_conv1d_focal_cv_4gpu.py": "Current ordinary-batch Conv1D focal grid: four fixed stratified folds, three training seeds, 25 fixed epochs, train-fold-only preprocessing, saved held-out probabilities and pooled OOF reconstruction. Supports one to four worker GPUs and scheduler-visible device mapping. Large near-copy of the other focal engines; selection evidence is not included in checkout.",
"tune_conv2d_focal_cv_4gpu.py": "Current Conv2D focal search with identical intended OOF selection protocol and Rare-F1-first ranking. Good complete-partition/row alignment and cache checks. Unlike the other focal engines, requires exactly four GPUs with direct fold/device mapping, creating a portability asymmetry. No current completed focal results are checked in.",
"tune_mlp_focal_cv_4gpu.py": "Current MLP focal OOF grid with train-only preprocessing, independent one-GPU worker fits, fixed budgets, complete pooled reconstruction and architecture-specific selected gamma. Supports allocation-aware queues. Shares extensive copied orchestration with the other focal engines, increasing maintenance drift risk.",
"tune_transformer_focal_cv_4gpu.py": "Current scalar-feature Transformer focal OOF search. Same folds, seeds, loss grid and primary metric as the other architectures; trains fixed epochs without held-out checkpointing. Supports one-to-four GPU workers. The model is a feature-token classifier, not a temporal Transformer IDS.",
"tune_conv2d_score_scaling_cv_4gpu.py": "Generic four-architecture engine for baseline CE, CE+batching and focal+batching OOF fits, plus shared vectorized score-pair metrics/scoring and cache identities. Reconstructs complete OOF arrays, preserves argmax tie behavior and selects shared seed coefficients by Rare-F1. Retention flags are diagnostic-only in current ranking. Also underlies numerous thin wrappers.",
"tune_conv2d_safe_stack_fusion.py": "Generic safe fusion engine for CE, focal and batching OOF experts. Searches class-specific simplex mixtures and margins with agreement support, then uses OOF Rare-F1 ranking. Explicitly treats same-OOF selection scores as development estimates. Architecture-specific wrappers reuse this engine.",
"tune_robust_calibrated_super_stack_all.py": "Largest meta-learning engine: training-fold temperatures, probability/disagreement features, scaled logistic stack, rare weights, blends, offsets, natural/subtype-balanced robustness metrics, convergence checks and resumable process caches. Nested meta-model fitting uses frozen backbone OOF arrays, so it is not fully nested expert retraining. Broad meta-function tests exist; current artifacts are absent.",
"tune_variant_specific_score_scaling.py": "Authoritative current eight-cell scorer. Independently selects R2L/U2R divisors for all four training regimes per architecture from OOF only, freezes a hashed manifest, then scores raw/scaled final test probabilities. Checks probability validity, common labels/folds, hashes and ambiguous sources. Final source semantic settings and independently loaded full benchmark labels/counts are insufficiently enforced; reproduced metadata gap is documented.",
"test_final_natural_rare_super_stack_kddtest.py": "Three tests for selected-config/source identity requirements, guarded rank handling and trained-state versus saved-state inference equivalence. Useful protection for post hoc stack evaluation. Does not validate the underlying CNN/Transformer training or eliminate frozen-expert CV dependence.",
"test_robust_calibrated_super_stack.py": "Twelve tests covering feature families, temperature/NLL behavior, sample weights, subtype equalization, confusion metrics, candidate counts, meta-state replay, caches/processes and a synthetic end-to-end meta workflow. Strongest tested subsystem, but independent from primitive focal/batching and full benchmark reproduction.",
"test_select_fusion_against_all_validation_baselines.py": "Seven tests for deliberate guard-policy changes, actual fusion-only candidate filtering, inclusive absolute gains, outer/inner acceptance requirements and correct complement refits. Documents selection semantics well. No full re-fitting of expert backbones within nested splits is tested or performed.",
"test_validation_filtered_fusion_kddtest_audit.py": "Nine tests for inclusive validation filtering, architecture handling, scaled generalist predictions, vectorized metrics, stack/cache tasks, progress and test-guard ranking. They validate the exploratory audit's operation; a passing audit is not evidence of fresh confirmatory test selection.",
"test_variant_specific_score_scaling.py": "Six tests covering OOF source selection including legacy fallback, probability/score checks, ambiguous test-source refusal, eight-cell summaries and synthetic selection/evaluation. Missing negative tests for final loss/gamma/quota mismatch, stale final cache identity and canonical full dataset labels/counts. Test fixtures intentionally use tiny arrays; all numerical tests remain unexecuted here due to absent dependencies."
}

for architecture, label in (("conv1d", "Conv1D"), ("conv2d", "Conv2D"), ("mlp", "MLP"), ("transformer", "Transformer")):
    NOTES[f"run_{architecture}_baseline_cv_4gpu.py"] = f"12-line {label} ordinary-CE OOF wrapper around the generic score-scaling CV engine. Requests baseline_ce and raw coefficients, providing the F=0/B=0 probability source for the modern factorial. Wrapper behavior is inherited rather than separately implemented."
    NOTES[f"run_{architecture}_batch_baseline_cv_4gpu.py"] = f"12-line {label} CE plus minority-guaranteed batching OOF wrapper. Requests baseline_batch and raw coefficients, supplying the F=0/B=1 source. The intervention includes replacement fill through BalancedBatchSequence."
    NOTES[f"run_{architecture}_focal_batch_cv_4gpu.py"] = f"12-line {label} focal plus guaranteed-batching OOF wrapper. Requests focal_balanced and raw coefficients. Its default architecture-specific focal settings must remain consistent with the selected focal-only search and final fitting specification."
    NOTES[f"tune_{architecture}_baseline_score_scaling_cv_4gpu.py"] = f"15-line {label} ordinary-CE score-scaling wrapper with the broader baseline coefficient grid. Uses shared OOF/scoring machinery; it is one source of baseline probabilities and legacy S settings. The later variant-specific selector applies a common grid independently to all four regimes."
    if architecture != "conv2d":
        NOTES[f"tune_{architecture}_score_scaling_cv_4gpu.py"] = f"Seven-line {label} wrapper around the generic score-scaling engine, defaulting to the architecture's focal+batching path. Reuses implementation and selection semantics; it is not a separate architecture-independent calibration method."
        NOTES[f"tune_{architecture}_safe_stack_fusion.py"] = f"Seven-line {label} wrapper around the safe-stack fusion engine. Sets architecture then inherits OOF expert validation, rare-score mixing and margin search. Belongs to the additional fusion research, not a new training toggle in the factorial."


def non_source_note(item):
    p = item["path"]
    suffix = Path(p).suffix
    if suffix == ".pyc":
        return "Interpreter bytecode cache. Hash/header inventoried; not executed. The corresponding .py is authoritative where present. Tracked caches from multiple Python versions should be excluded from reproducible source distribution; some cache names have no matching current source."
    if p.startswith("images/"):
        group = p.split("/")[1]
        return f"Historical {group} feature-grid illustration; 369x369 RGBA render of an encoded 11x11 grid. CRC checked, decoded and included in the reviewed 63-image contact sheet. Only indices 0-20 are supplied. Current training reads tabular arrays directly, so this PNG is not an active model input file."
    specifics = {
        "README.md": "Original 2024/25 CNN/CTGAN thesis description, dependency overview and old result figure links. Does not explain the new four-backbone factorial, OOF commands or artifact schemas. References absent LICENSE; acknowledges incomplete synthetic/image collections. Rewrite around the current study while explicitly preserving historical context.",
        "dependencies_utilized.txt": "534-line historical listings of two broad Spyder environments. Contains Python 3.19.8 typo; second environment combines TF2.18 with NumPy1.23.5 despite official TF requirement >=1.26. Not a tested installable lock for current code, which also needs Python>=3.10 for strict zip usage.",
        ".vscode/extensions.json": "Existing untracked editor configuration with empty extension recommendations. No experimental effect. Included in original file inventory; not changed by the review.",
        "data/KDDTrain+.txt": "Complete 125,973-row/43-field benchmark training file; every row read, numeric finiteness checked, subtype/class counts and predictor duplicate/overlap statistics computed. Supplies all modern fitting/selection data. 52 U2R and 995 R2L rows; hash recorded in inventory/dataset audit.",
        "data/KDDTest+.txt": "Complete 22,544-row/43-field benchmark test file; every row audited. Repo mapping gives 67 U2R/2,887 R2L; httptunnel sensitivity yields 200/2,754. Seventeen test-only subtypes and 664 predictor-overlapping test rows. Preserve for frozen evaluation rather than tuning; source hash recorded.",
        "data/train_labels.csv": "125,973 filename/class rows, supports matching raw train mapping. Historical image index; only 21 referenced train PNGs are included. Modern tabular training does not rely on these filenames. All rows and widths checked.",
        "data/test_labels.csv": "22,544 filename/class rows matching the repo's test mapping, including U2R support67. Only 21 referenced test PNGs are supplied. This label convention must be documented for comparison with other NSL-KDD papers. All rows checked.",
        "data/synth_labels.csv": "35,134 historical synthetic image-label rows: Probe32,278, R2L2,713, U2R143. Only 21 synthetic PNGs supplied and no corresponding complete synthetic tabular dataset. Records a largely Probe-heavy old augmentation, not data used in the current no-CTGAN factorial.",
        "figures/GAN_Figure.png": "Educational generator/discriminator flow with noise, artificial data and true/false discrimination. Visually inspected and CRC checked. Conceptual legacy GAN illustration, not a detailed current CTGAN or factorial protocol diagram.",
        "figures/OHE_Figure.png": "Educational one-hot encoding illustration. Correct conceptual categorical-to-indicator mapping; visually inspected and CRC checked. Does not specify current canonical category lists, feature order or fold-only fitting.",
        "figures/Tab-Image-Figure.png": "Educational tabular-value-to-image-grid illustration. Visually inspected and CRC checked. Clarify that the CNN uses reshaped numeric arrays rather than learning from exported plotting images or packet photographs.",
        "figures/Revised_Proposed_Model.png": "Legacy method flow containing CTGAN, image conversion, random undersampling and CNN fitting. Visually inspected and CRC checked. It conflicts with the no-CTGAN/current factorial narrative if presented as that study's pipeline diagram.",
        "figures/balance-figure.png": "Old raw/CTGAN-augmented/undersampled class-count charts. Augmented total161,107 and undersampled total82,903 belong to the historical thesis. Visually inspected; does not describe modern per-batch exposure or actual modern training rows.",
        "figures/cnn_model-revised.png": "Old valid-convolution small-CNN architecture illustration, compatible with the saved roughly55k-weight model. Visually inspected and CRC checked. Do not use as the figure for the current residual/BN matched Conv2D backbone.",
        "model/cnn_model_best_0.8699876070022583.h5": "703,128-byte legacy HDF5 model. Signature and embedded JSON reveal 11x11 valid-convolution CNN, leaky-ReLU second conv, dense256/softmax and CE/Adam training. Weights not loaded/executed. Not the current109k backbone; no complete fitted preprocessing bundle accompanies it.",
        "results/results.txt": "Legacy summary: test accuracy86.9988%, MCC0.8080, R2L F1~0.7432, U2R F1~0.16 and U2R recall6/67. Rare-F1~45.16% differs from abstract protocol. Claims25epochs and a10fold score without matching contemporary manifest; not modern factorial evidence.",
        "results/training_results.txt": "100-epoch historical training log; corresponds in length to available training curve, whereas results.txt says25. No run identity ties these artifacts together. Read as old training output, not evidence that the modern fixed25epoch protocol was run.",
        "results/cnn_training_plot.png": "Legacy100epoch training/validation accuracy plot: training rises near0.98 while validation fluctuates roughly0.87-0.96. Visually inspected/CRC checked. Does not provide rare-class learning curves or the new fixed25epoch evidence.",
        "results/confusion_matrix_heatmap.png": "Legacy five-class count matrix with only6 correctly detected U2R samples of67, despite~87% overall accuracy. Counts support the old report, not current factorial cells. Visually inspected/CRC checked; useful demonstration of why rare metrics matter.",
        "results/normalized_confusion_matrix_heatmap.png": "Row-normalized form of the legacy confusion matrix: U2R recall~0.09, with~0.45 predictedR2L and~0.42Normal. Visually inspected/CRC checked. It illustrates rare false negatives but provides no model-seed factorial comparison.",
        "results/multi_class_auc.png": "Legacy one-vs-rest ROC curves, including U2R AUC~0.93. Visually inspected/CRC checked. High ranking AUC coexists with poor U2R argmax recall; include decision metrics and precision-recall analysis for rare attacks rather than using this as sufficient evidence.",
        "results/cnn2d_grid_plan.csv": "324 planned run rows (108 beta/gamma configurations x3seeds), with9 beta values and12 gamma values at one synthetic-count setting. All rows/schema checked. This is an older plan, not completed predictions or the modern18candidate per-architecture focal selection.",
        "slurm/run_cnn_baseline_h200.sbatch": "Legacy one-H200 Slurm launch with hardcoded site paths/conda environment,16CPUs,128GB and12h. Launches the old baseline. Allocation-specific template requires adaptation; no job was submitted during review.",
        "slurm/run_cnn_opt_1d_4gpu.sbatch": "Old four-GPU mirrored Conv1D/CTGAN Slurm launch with fixed cluster paths and12h allocation. This is different from modern independent single-GPU fold fits. No submission evidence is provided by the script itself.",
        "slurm/run_random_search_cnn_opt_1d_4gpu.sbatch": "Old four-GPU500trial random-search job with three-day budget and site-specific environment/paths. Helpful launch template but computationally expensive and unrelated to proof of modern factorial results. Not executed.",
        "slurm/run_mlp_focal_cv_firebird.sbatch": "Modern MLP focal four-fold CV launch on two L40S GPUs,64GB,12h, using worker queue --gpus0 1. Better matches current CV scheduling. Still cluster-specific; does not launch all factorial stages or prove completion."
    }
    if p in specifics:
        return specifics[p]
    if suffix == ".log":
        return "Unrelated Malwarebytes installer log under a literal Windows-style %localappdata% directory. Text read and inventoried without reproducing personal machine details. No role in ML/cyber intrusion experiments; remove from research distribution."
    raise ValueError("Missing individual review note: " + p)


def main():
    items = list(csv.DictReader((OUT / "file_inventory.csv").open()))
    sources = {x["path"]: x for x in json.loads((OUT / "source_map.json").read_text())}
    assert len(items) == 220
    actual_names = {Path(p).name for p in sources}
    assert actual_names == set(NOTES), (actual_names - set(NOTES), set(NOTES) - actual_names)
    lines = ["# Every-file review", "", "Companion to [the research audit](REPOSITORY_REVIEW.md). All 220 original files outside .git and review-generated analysis/ are represented below. Source notes distinguish current study machinery, legacy paths and later fusion work. Hashes and format checks for every file are in [file_inventory.csv](file_inventory.csv); function line locations are in [source_map.json](source_map.json). Bytecode is treated as derived opaque cache data rather than executed code. All numerical test modules were read but could not import in the dependency-free local environment.", ""]
    current = None
    for item in items:
        path = item["path"]
        folder = str(Path(path).parent)
        if folder != current:
            lines += [f"## {folder}", "", "| File | Size / source lines | Review |", "|---|---:|---|"]
            current = folder
        if path in sources:
            note = NOTES[Path(path).name]
            size = f'{int(item["bytes"]):,} B / {sources[path]["lines"]:,} lines'
        else:
            note = non_source_note(item)
            size = f'{int(item["bytes"]):,} B'
        note = note.replace("|", "\\|")
        lines.append(f'| [{path}](../{path}) | {size} | {note} |')
        next_index = items.index(item) + 1
        if next_index == len(items) or str(Path(items[next_index]["path"]).parent) != current:
            lines.append("")
    (OUT / "FILE_BY_FILE_REVIEW.md").write_text("\n".join(lines) + "\n")
    print(f"Reviewed rows: {len(items)}; source notes: {len(NOTES)}")


if __name__ == "__main__":
    main()
